[project]
name = "specless"
version = "0.0.2"
description = "Package to learn specification and synthesize strategy from demonstrations"
authors = [{name = "Kandai Watanabe, email = "kandai.wata@gmail.com"}]
license = {file = "LICENSE"}
readme = "README.md"
dynamic = ["dependencies", "optional-dependencies"]
requires-python = ">= 3.8"

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}
optional-dependencies = {dev = { file = ["requirements-dev.txt"] }}

[tool.poetry]
name = "specless"
version = "0.0.2"
description = "Package to learn specification and synthesize strategy from demonstrations"
authors = ["Kandai Watanabe <kandai.wata@gmail.com>"]
license = "LICENSE"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[project.urls]
Repository = "https://github.com/watakandai/specless"
Documentation = "https://watakandai.github.io/specless/"
