name: "Pull Request Docs Check"

on:
- pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python3 -m pip install -r requirements.txt && python3 -m pip install -r docs/requirements.txt
    - name: Sphinx build
      run: |
        python3 -m sphinx docs docs/html
    # - name: Upload artifacts
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: html-docs
    #     path: docs/html
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      # if: github.ref == 'refs/heads/main'
      with:
        publish_branch: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
